### ISSUE TITLE
Adding device to Favorites with multiple nodes.  UD IOS 0.3.7

### ISSUE THREAD

**Issue by gcjacobs** [UniversalDevicesInc/UD-Mobile-iOS#41]
Problems with adding Insteon devices with multiple nodes to Favorites such as 2450 IOLinc. The 2450 has two nodes, a sensor, and a relay. When selecting the sensor the only node available, is the relay.  I tested other devices with multiple nodes and they react the same way.
[Screenshot #2.pdf](https://github.com/UniversalDevicesInc/UD-Mobile-iOS/files/6912175/Screenshot.2.pdf)

Also, I'm no longer able to delete nodes from Favorites.

**Comment by JavierRefuerzo** [comment]
Hi @gcjacobs ,
I ran a test but could not reproduce the issue, it may just be the process has changed.  When you select a node with grouped children (grouped nodes) both the Display Status and the Grouped nodes are shown.  If the a display status (i.e. Status line in your image) is selected this will create the favorite if grouped node is selected (i.e. Garage Front-Relay in your image) the "Select Display Status is shown for the child  node.  I update the wiki to show how to delete Favorites for both platforms. iOS will soon change to match Android and be more intuitive. 

Wiki:
https://wiki.universal-devices.com/index.php?title=UD_Mobile#Favorites

Android implementation:
https://youtu.be/WvZd7XH5Bxs

**Comment by gcjacobs** [comment]
Hi Javi,
I find the new process of adding a device to Favorites with multiple nodes very confusing.

Here is a different example: a 2421 TriggerLinc which has three nodes open, closed and heartbeat.
See screenshot #1 which is the list of Garage devices.  I selected GarageDoorRear see Screenshot #2.  
GarageDoorRear (which is the open node) is not displayed.
If I tap the three dots (Screenshot #3) GarageDoorRear again is not displayed. 

It's not intuitive, that all I need to do is tap the screen to get the node I want, which is not displayed.

Can you display all the nodes in the device? 
Regards,
Gerry
The Helix Group, Inc.
919-870-9345 O
919-676-7435 F
919-539-3198 C
www.helixgroup.com <http://www.helixgroup.com/>

**Comment by JavierRefuerzo** [comment]
Hi @gcjacobs ,

I do understand the confusion, we will keep this in mind as we continue to develop.  Currently only a single status can be displayed on the Favorites tab, if a user would like to view another status of the same node, another favorite can be created.  

Were you able to select the status you desired?  There is only one screenshot attached to this issue, so if the issue is not solved please include the other screenshots so we can investigate.

**Comment by gcjacobs** [comment]
Hi Javi.
It appears that I can’t describe the problem clearly. 

The 2421 TriggerLink has three nodes: open, closed and heartbeat.
When you try to add the open node to Favorites it's not visible, only the closed and heartbeat are visible. See screenshots #2 and #3

I finally figured out that taping the top of the box will add the open node to my Favorites.
To me the default for selection should be the primary node ie Open.

I have made sure the attachments are there.

Regards
Gerry
The Helix Group, Inc.
919-870-9345 O
919-676-7435 F
919-539-3198 C
www.helixgroup.com <http://www.helixgroup.com/>

**Comment by JavierRefuerzo** [comment]
Hi @gcjacobs ,

It is very possible GitHub is not showing attachments in email replies. So the screen shots will need to be attached from the web version of this issue within a comment.   See here https://github.com/UniversalDevicesInc/UD-Mobile-iOS/issues/41 .

I have tested a TriggerLink and all three nodes are available, so if they are not showing it may be a bug.  I'll take a look at your screenshots  when available.

**Comment by gcjacobs** [comment]
Javi,
Here are the three screenshots:
![Screenshot #1](https://user-images.githubusercontent.com/57806702/127907044-126e2ade-c9f3-49ce-8fd5-37d5a8d6cac0.png)
![Screenshot #2](https://user-images.githubusercontent.com/57806702/127907054-94c8f056-5ac1-4a9c-9dc3-214a9fc3ef1f.png)
![Screenshot #3](https://user-images.githubusercontent.com/57806702/127907063-2ad1c014-f404-4598-b2ee-916cdf505486.png)
Screenshot #3 has GarageDoorRear visible but its nonfunctional.

**Comment by gcjacobs** [comment]
Hi Javi,
I have uploaded the three screenshots to GitHub issue #41. 

Regards,
Gerry
The Helix Group, Inc.
919-870-9345 O
919-676-7435 F
919-539-3198 C
www.helixgroup.com <http://www.helixgroup.com/>

**Comment by JavierRefuerzo** [comment]
Thank you.  So issue is resolved?  I do understand it could be less confusing.

**Comment by gcjacobs** [comment]
Javi, 
No, the issue is not resolved. 

It's not that it's confusing, it’s that it doesn’t work correctly. 

I had 8 nodes installed in Favorites up to version 0.3.6 without any confusion or problems.

All my reported issues began with version 0.3.7.

Can you do a remote connect to my iPhone? I can’t seem to articulate the problem but I can defiantly demo the problem.

Regards,
Gerry
The Helix Group, Inc.
919-870-9345 O
919-676-7435 F
919-539-3198 C
www.helixgroup.com <http://www.helixgroup.com/>

**Comment by JavierRefuerzo** [comment]
Hi @gcjacobs ,

I have circled the click location in the attached image.  The only difference from earlier versions is that grouped nodes are now included in the list along with status-values.  This is only the case when the main parent of a group is selected, and was done as some users had difficulty finding grouped nodes when selecting a new Favorite. 

In the attached image the sensor node (open) is the parent of the group.  Closed and Heartbeat are children.  If "Status" is selected the sensor (open) node is selected along and the status-value named "Status" .   If any of the children (grouped nodes) are selected the user will be prompted to select a visible-status-value for that node.

Currently Favorite items can only show one status-value for a selected node. The trigger link has three nodes all of which have a status-values named "Status".  Nodes can have multiple status values such as "On-Level", "Ramp-Rate", "Cool-Set-Point" , "Status" ,Humidity, ect.
![openSensor](https://user-images.githubusercontent.com/14967116/128031925-17f68046-a45f-4686-b2b3-0177ff924bd0.png)

**Comment by gcjacobs** [comment]
Javi,
Your comment "The only difference from earlier versions is that grouped nodes are now included in the list along with status-values.”
There is an additional difference, the parent is not listed in the group.  That's what caused me the most confusion. 

I suggest you revert to the prior version:
In my case I have 261 Insteon devices of which 26 have the parent/child options. Of that 26, all use the parent option in any logic 
or programs, none use a child option.

As you stated, the current Favorite process can only show one status-value. Therefore, the process prior to 0.3.7, which favors 
the parent option, would better serve a larger user population, as the user population using the child options is relatively small.

Regards,
Gerry
